/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Jul 20 11:31:38 2016. */

#include "sensor_data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorDataMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SensorDataMessage, lucky_number, lucky_number, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
